### ISSUE TITLE
Dockprom failing to build due to ssl version error

### ISSUE THREAD

**Issue by Sprooty** [stefanprodan/dockprom#293]
Instructions as per readme result in,

```
 dockprom git:(master) ADMIN_USER='admin' ADMIN_PASSWORD='admin' ADMIN_PASSWORD_HASH='$2a$14$1l.IozJx7xQRVmlkEQ32OeEEfP5mRxTpbDTCTcXRqn19gXD8YK1pO' docker-compose up -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
```

- Ubuntu 22.04
- Docker version 20.10.23, build 7155243
- Docker Compose version v2.24.2

**Comment by nightah** [comment]
The SSL error is being output by docker-compose. The version of compose is actually 1.x per the logs you have provided.

It looks like your OS doesn't have the wrapper script which makes 'docker-compose' run compose v2.

Try replace the 'docker-compose up -d' part of the command with 'docker compose up -d'.

**Comment by Sprooty** [comment]
This worked thanks!
