### ISSUE TITLE
Not working some of the graphs

### ISSUE THREAD

**Issue by ionutz89** [stefanprodan/dockprom#63]
Hi,

On dashboard docker containers, the storage load does not work and I have those errors:

Error: Multiple Series Error
    at e.setValues (http://localhost:3000/public/build/0.be20b78823b4c9d93a84.js:7:277367)
    at e.onDataReceived (http://localhost:3000/public/build/0.be20b78823b4c9d93a84.js:7:274881)
    at o.emit (http://localhost:3000/public/build/vendor.2305a8e1d478628b1297.js:15:520749)
    at t.emit (http://localhost:3000/public/build/app.5331f559bd9a1bed9a93.js:1:29217)
    at e.handleQueryResult (http://localhost:3000/public/build/0.be20b78823b4c9d93a84.js:7:19860)

Container Memory usage, Sample Ingested 5M rate and container cached memory usage do not show anything.

I am using Debian OS like the host for Docker containers.

Thank you,
Ionut

**Comment by stefanprodan** [comment]
You probably have multiple mount points, take a look at #49

**Comment by ionutz89** [comment]
Thank you. It is working the storage load now. 

What about this "Container Memory usage, Sample Ingested 5M rate and container cached memory usage do not show anything." ?
